[build]
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=mold", "-Clink-arg=-Wl,--no-rosegment"]

[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-linux-gnu-gcc"
#rustflags = ["-Ctarget-cpu=cortex-a53"]

linker = "/usr/bin/clang"
rustflags = ["-Ctarget-cpu=cortex-a53", "-Clink-args=-target aarch64-unknown-linux-gnu --sysroot=/usr/aarch64-linux-gnu/ -fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "-L/usr/lib/aarch64-linux-gnu/"]